### ISSUE TITLE
Error when freshly installing the plugin

### ISSUE THREAD

**Issue by Syrilai** [kelvin124124/ChatTranslated#51]
When freshly installing the plugin, it errors out and fails to initialize.

```
00:15:45.347 | ERR | [LOCALPLUGIN] Error while loading "ChatTranslated", failed to bind and call the plugin constructor
	System.AggregateException: Failed to create ChatTranslated.Plugin (ctor invocation) (Exception has been thrown by the target of an invocation.)
	 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
	 ---> System.NullReferenceException: Object reference not set to an instance of an object.
	   at ChatTranslated.Plugin..ctor(IDalamudPluginInterface pluginInterface, ICommandManager commandManager) in /work/repo/ChatTranslated/Plugin.cs:line 69
	   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   --- End of inner exception stack trace ---
	   at System.Reflection.MethodBaseInvoker.InvokeConstructorWithoutAlloc(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
	   at System.Reflection.MethodBase.Invoke(Object obj, Object[] parameters)
	   at Dalamud.IoC.Internal.ServiceContainer.<>c__DisplayClass10_0.<CreateAsync>b__0() in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 117
	--- End of stack trace from previous location ---
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 129
	   --- End of inner exception stack trace ---
	   at Dalamud.IoC.Internal.ServiceContainer.CreateAsync(Type objectType, Object[] scopedObjects, IServiceScope scope) in C:\goatsoft\companysecrets\dalamud\\IoC\Internal\ServiceContainer.cs:line 136
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.<>c__DisplayClass75_0.<<CreatePluginInstance>g__Create|0>d.MoveNext() in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 583
	--- End of stack trace from previous location ---
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.CreatePluginInstance(LocalPluginManifest manifest, IServiceScope scope, Type type, DalamudPluginInterface dalamudInterface) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 581
	   at Dalamud.Plugin.Internal.Types.LocalPlugin.LoadAsync(PluginLoadReason reason, Boolean reloading) in C:\goatsoft\companysecrets\dalamud\\Plugin\Internal\Types\LocalPlugin.cs:line 396
```

This is, as to what I can see, happening because of the config migration trying to access a config value that, well, never existed in the first place.

**Comment by kelvin124124** [comment]
fixed
